version: 2.1

executors:
  deploy_executor:
    docker:
      - image: php:8.0-apache-buster

jobs:
  deploy_job:
    parallelism: 1
    executor: deploy_executor
    working_directory: /var/www/html
    steps:
      - checkout
      - run:
          name: install
          command: |
            apt update && apt install -y software-properties-common
            curl -sS https://getcomposer.org/installer
            mv composer.phar /usr/local/bin/composer
      - run:
          name: composer install
          command: /usr/local/bin/composer install -n --prefer-dist
      - run:
          name: GCP Auth
          command: |
            echo $GKE_SERVICE_KEY > gcloud-service-key.json
            gcloud auth activate-service-account --key-file gcloud-service-key.json
            gcloud auth configure-docker us-east1-docker.pkg.dev
      - run:
          name: gcloud install
          command: |
            curl -s https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-370.0.0-darwin-x86_64.tar.gz?hl=ja | tar xz
            source ./google-cloud-sdk/path.bash.inc
            gcloud components install kubectl
            gcloud config set project o-taiji
            gcloud config set compute/zone us-west1-a
            gcloud container clusters get-credentials allabout-ogawa-kubernetes
      - run:
          name: build image
          command: |
            docker build -t us-east1-docker.pkg.dev/o-taiji/allabout-ogawa-kubernetes/app:${CIRCLE_SHA1} .
      - run:
          name: push image
          command: |
            docker push us-east1-docker.pkg.dev/o-taiji/allabout-ogawa-kubernetes/app:${CIRCLE_SHA1}
      - run:
          name: deploy
          command: |
            kubectl set image deployment/app app=us-east1-docker.pkg.dev/o-taiji/allabout-ogawa-kubernetes/app:${CIRCLE_SHA1}

workflows:
  deploy_workflow:
    jobs:
      - deploy_job:
        filters:
          branches:
            only: main
