version: 2.1

executors:
  build_executor:
    docker:
      - image: ubuntu:22.04
  deploy_executor:
    docker:
      - image: php:8.0-apache-buster

jobs:
  build_job:
    parallelism: 1
    executor: build_executor
    steps:
      - checkout
      - run:
          name: tool install
          command: |
            apt update && apt install -y software-properties-common zip unzip
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
            mv composer.phar /usr/local/bin/composer
      - run:
          name: app install
          command: |
            cd src
            echo $LARAVEL_ENV | base64 --decode > .env
            /usr/local/bin/composer install -n --prefer-dist
      - run:
          name: build image
          command: |
            cd /var/www
            docker build -t us-east1-docker.pkg.dev/o-taiji/allabout-ogawa-kubernetes/app:${CIRCLE_SHA1} .
      - run:
          name: push image
          command: |
            docker push us-east1-docker.pkg.dev/o-taiji/allabout-ogawa-kubernetes/app:${CIRCLE_SHA1}
      - run:
          name: gcloud install
          command: |
            curl -s https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-370.0.0-darwin-x86_64.tar.gz?hl=ja | tar xz
            source ./google-cloud-sdk/path.bash.inc
            echo $GKE_SERVICE_KEY > gcloud-service-key.json
            gcloud auth activate-service-account --key-file gcloud-service-key.json
            gcloud auth configure-docker us-east1-docker.pkg.dev
            gcloud components install kubectl
            gcloud config set project o-taiji
            gcloud config set compute/region us-west1
            gcloud container clusters get-credentials allabout-ogawa-kubernetes
  deploy_job:
    parallelism: 1
    executor: deploy_executor
    steps:
      - run:
          name: deploy
          command: |
            kubectl set image deployment/app app=us-east1-docker.pkg.dev/o-taiji/allabout-ogawa-kubernetes/app:${CIRCLE_SHA1}

workflows:
  deploy_workflow:
    jobs:
      - build_job:
      - deploy_job:
        filters:
          branches:
            only: main
