apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: ${NAMESPACE}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: ${DEPLOYMENT_CONTAINER_IMAGE}
          name: app
          ports:
            - name: http
              containerPort: 80
          env:
            - name: TZ
              value: Asia/Tokyo

