apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${NAMESPACE}
  name: app
  labels:
    run: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: gcr.io/google-samples/hello-app:1.0
          name: app-container
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 512Mi
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            protocol: TCP
          env:
            - name: TZ
              value: Asia/Tokyo
