apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${NAMESPACE}
  name: app
  labels:
    run: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: gcr.io/google-samples/hello-app:1.0
          name: app-container
          ports:
            - name: http
            - containerPort: 80