apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: ${CIRCLE_PROJECT_REPONAME}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ${CIRCLE_PROJECT_REPONAME}-ip
    networking.gke.io/managed-certificates: cert
spec:
  defaultBackend:
    service:
      name: service
      port:
        number: 80